
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: kamisystem
      MYSQL_USER: kamisystem
      MYSQL_PASSWORD: kamisystem123
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - DATABASE_URL=mysql+pymysql://kamisystem:kamisystem123@mysql:3306/kamisystem
      - TZ=Asia/Shanghai
    volumes:
      - ./web/exports:/app/exports
    restart: unless-stopped

volumes:
  mysql_data:
